---
- name: install common packages
  become: yes
  action: apt pkg={{item}} state=installed
  with_items:
    - git
    - lsof
    - vim
    - bc
    - curl
    - wget
    - di
    - htop
    - ncdu
    - pv
    - ranger
    - rsync
    - tmux
    - zsh
    - aptitude
- name: pull dotfiles
  git: repo=https://github.com/alexwh/dotfiles.git dest=~/dotfiles force=yes
  register: dotfiles_pulled
- name: install dotfiles
  shell: ~/dotfiles/install
  register: installoutput
  changed_when: "'Creating link' in installoutput.stdout or 'checked out' in installoutput.stdout"
  when: dotfiles_pulled|success
- name: copy zshrc_local
  copy: src=zshrc_local dest=~/.zshrc_local force=no
- name: change shell to zsh
  become: yes
  user: name="{{ ansible_user_id }}" shell=/bin/zsh
- name: remove motd
  become: yes
  copy: content="" dest=/etc/motd force=yes
