---
- name: add ssh keys to target
  authorized_key: user={{ ansible_user_id }} key="{{ lookup('file', item) }}"
  with_fileglob:
    - ~/.ssh/*.pub
  register: add_identity_key

- name: disable empty passwords
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
  notify: restart sshd

- name: disable password root logins
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin without-password"
  notify: restart sshd

- name: disable password login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  when: add_identity_key|success and not add_identity_key|skipped
  notify: restart sshd
